### ISSUE TITLE
Fix server.js's Qr code please 🥺 

### ISSUE THREAD

**Issue by bilal-08** [Hidayatilman/ShiraoriBOT#1]
The Qr code in app.heroku.com/views
is so small that it couldn't be able to be scanned

**Comment by Hidayatilman** [comment]
try using node . --server in terminal heroku
Or node . --big-qr

**Comment by bilal-08** [comment]
thanks will do

**Comment by bilal-08** [comment]
> try using node . --server in terminal heroku
> Or node . --big-qr

I did and it's same and the qr code is not Different all time TwT
i even tried Qr-image npm package but again nothing changes

**Comment by Hidayatilman** [comment]
GK tau🤔

**Comment by bilal-08** [comment]
> GK tau🤔

who's GK?👀

**Comment by Hidayatilman** [comment]
> > try using node . --server in terminal heroku
> > Or node . --big-qr
> 
> I did and it's same and the qr code is not Different all time TwT
> i even tried Qr-image npm package but again nothing changes

Better to add files session.data.json In order not to need scan Again
